spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
  session-timeout: 30
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
  port: 8202
  session-timeout: 30
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-test.com:7001/eureka/
